const cities = [
    "Perth",
    "Poole",
    "Rochdale",
    "Rotherhithe",
    "Salford",
    "Sutton",
    "Swansea",
    "Warrington",
    "Bath",
    "Bromsgrove",
    "Cheltenham",
    "Clapham",
    "Cobham",
    "Cramlington",
    "Croydon",
    "Hampstead",
    "Harrogate",
    "Houghton-Le-Spring",
    "Milton Keynes",
    "Penarth",
    "Whitley Bay",
    "Wythenshawe",
    "Fulham",
    "Leeds",
    "Wilmslow",
    "Durham",
    "Pontypridd",
    "Washington",
    "Newport",
    "Sale",
    "Nottingham",
    "Liverpool",
    "Bolton",
    "Gateshead",
    "Dagenham",
    "St Albans",
    "Stockport",
    "Sunderland",
    "Sutton Coldfield",
    "North Shields",
    "Wallsend",
    "Belfast",
    "Islington",
    "Cardiff",
    "Birmingham",
    "Glasgow",
    "London",
    "Newcastle upon Tyne",
    "Manchester",
    "Bristol"
];

module.exports = {
    cities
};